//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public Aluno()
        {
            this.TurmaAluno = new HashSet<TurmaAluno>();
        }
    
        public int IdAluno { get; set; }
        public Nullable<int> Matricula { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<TurmaAluno> TurmaAluno { get; set; }
    }
}
