//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarioHorario
    {
        public CalendarioHorario()
        {
            this.HorarioRecursoSolicitado = new HashSet<HorarioRecursoSolicitado>();
        }
    
        public string IdCalendarioHorario { get; set; }
        public Nullable<System.DateTime> InicioHorario { get; set; }
        public Nullable<System.DateTime> FimHorario { get; set; }
    
        public virtual ICollection<HorarioRecursoSolicitado> HorarioRecursoSolicitado { get; set; }
    }
}
