//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplina
    {
        public Disciplina()
        {
            this.ProfessorDisciplina = new HashSet<ProfessorDisciplina>();
            this.TurmaProfessorDisciplina = new HashSet<TurmaProfessorDisciplina>();
        }
    
        public int IdDisciplina { get; set; }
        public string NomeDisciplina { get; set; }
        public string Semestre { get; set; }
    
        public virtual ICollection<ProfessorDisciplina> ProfessorDisciplina { get; set; }
        public virtual ICollection<TurmaProfessorDisciplina> TurmaProfessorDisciplina { get; set; }
    }
}
