//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioRecursoComputacional
    {
        public string IdHorarioRecursoComputacional { get; set; }
        public string IdHorario { get; set; }
        public Nullable<int> IdRecursoComputacionalFK { get; set; }
    }
}
