//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioRecursoSolicitado
    {
        public HorarioRecursoSolicitado()
        {
            this.RecursosAlocados = new HashSet<RecursosAlocados>();
        }
    
        public int IdHorarioRecursoSolicitado { get; set; }
        public string IdCalendarioHorario { get; set; }
        public int IdRecursoSolicitado { get; set; }
    
        public virtual CalendarioHorario CalendarioHorario { get; set; }
        public virtual RecursoSolicitado RecursoSolicitado { get; set; }
        public virtual ICollection<RecursosAlocados> RecursosAlocados { get; set; }
    }
}
