//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DesenvolvimentoLocalEntities : DbContext
    {
        public DesenvolvimentoLocalEntities()
            : base("name=DesenvolvimentoLocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aluno> Aluno { get; set; }
        public virtual DbSet<CalendarioHorario> CalendarioHorario { get; set; }
        public virtual DbSet<Disciplina> Disciplina { get; set; }
        public virtual DbSet<HorarioRecursoComputacional> HorarioRecursoComputacional { get; set; }
        public virtual DbSet<HorarioRecursoSolicitado> HorarioRecursoSolicitado { get; set; }
        public virtual DbSet<Professor> Professor { get; set; }
        public virtual DbSet<ProfessorDisciplina> ProfessorDisciplina { get; set; }
        public virtual DbSet<RecursoComputacional> RecursoComputacional { get; set; }
        public virtual DbSet<RecursosAlocados> RecursosAlocados { get; set; }
        public virtual DbSet<RecursoSolicitado> RecursoSolicitado { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<Turma> Turma { get; set; }
        public virtual DbSet<TurmaAluno> TurmaAluno { get; set; }
        public virtual DbSet<TurmaProfessor> TurmaProfessor { get; set; }
        public virtual DbSet<TurmaProfessorDisciplina> TurmaProfessorDisciplina { get; set; }
    }
}
