//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        public Professor()
        {
            this.ProfessorDisciplina = new HashSet<ProfessorDisciplina>();
            this.TurmaProfessor = new HashSet<TurmaProfessor>();
        }
    
        public string IdProfessor { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string CPF { get; set; }
        public Nullable<int> RG { get; set; }
    
        public virtual ICollection<ProfessorDisciplina> ProfessorDisciplina { get; set; }
        public virtual ICollection<TurmaProfessor> TurmaProfessor { get; set; }
    }
}
