//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecursosAlocados
    {
        public int IdRecursoAlocado { get; set; }
        public int IdHorarioRecursoSolicitado { get; set; }
        public int IdTurmaProfessorDisciplina { get; set; }
    
        public virtual HorarioRecursoSolicitado HorarioRecursoSolicitado { get; set; }
    }
}
