//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public Sala()
        {
            this.RecursoComputacional = new HashSet<RecursoComputacional>();
        }
    
        public string IdSala { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> QuantVagas { get; set; }
    
        public virtual ICollection<RecursoComputacional> RecursoComputacional { get; set; }
    }
}
