//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turma
    {
        public Turma()
        {
            this.TurmaAluno = new HashSet<TurmaAluno>();
            this.TurmaProfessor = new HashSet<TurmaProfessor>();
        }
    
        public int IdTurma { get; set; }
        public Nullable<int> Numero { get; set; }
    
        public virtual ICollection<TurmaAluno> TurmaAluno { get; set; }
        public virtual ICollection<TurmaProfessor> TurmaProfessor { get; set; }
    }
}
